[package]
name = "curl"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
url = "2.5.2"
structopt = "0.3.26"
serde = "1.0.213"
serde_json = "1.0.132"

